CS2113-AY1819S2-T09-3/main

- build.gradle
- docs/UserGuide.adoc
> [v1.1] Update User Guide to match product specification

- docs/UserGuide.adoc
- src/main/java/seedu/address/storage/AddressBookStorage.java
- src/main/java/seedu/address/storage/JsonAddressBookStorage.java
- src/main/java/seedu/address/storage/StorageManager.java
> [v1.1] Add export feature for local storage

- docs/DeveloperGuide.adoc
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/resources/view/StatusBarFooter.fxml
- src/test/java/seedu/address/ui/StatusBarFooterTest.java
> [v1.1] Update Developer Guide to match product specification

- docs/DeveloperGuide.adoc
> [v1.2] Update Developer Guide with implementation of import/export enhancement

- docs/DeveloperGuide.adoc
Please note that what was written here are summaries of what is currently being implemented at PR #79 that is currently still work in progress. It will be updated once the feature is completed at v1.3.
Closes #74
> Update Developer Guide with implementation of list tag feature implementation

- docs/DeveloperGuide.adoc
> [v1.2] Update developer guide with implementation of command aliases and calendar

- docs/UserGuide.adoc
> Update User Guide, Section 5.2.7, 6.2.10, 7, 8, Appendix

- docs/UserGuide.adoc
> Update User Guide, Section 5 - 5.2.6

- docs/UserGuide.adoc
> Update User Guide, Section 6.2.5 - 6.2.10

- docs/UserGuide.adoc
> Update User Guide, Section 6.1 - 6.2.4

- src/main/java/seedu/project/logic/commands/ListCommand.java
- src/main/java/seedu/project/logic/commands/ListProjectCommand.java
> [v1.3] Add List Command for Project and Task

- src/main/java/seedu/project/logic/LogicManager.java
- src/main/java/seedu/project/logic/commands/ExportCommand.java
- src/main/java/seedu/project/logic/commands/ListProjectCommand.java
- src/main/java/seedu/project/logic/parser/ExportCommandParser.java
- src/main/java/seedu/project/ui/MainWindow.java
> [v1.3] Fix interaction between Project and Task and bugs at export feature

- docs/UserGuide.adoc
- src/main/java/seedu/project/logic/commands/CompletedCommand.java
- src/main/java/seedu/project/logic/parser/CompletedCommandParser.java
- src/main/java/seedu/project/logic/parser/ProjectParser.java
> [v1.3] Add CompletedCommand as part of analyse feature

- .gitignore
- _response/config.json
> Reposense unable to identify authors despite populated commit history

- src/main/java/seedu/project/logic/commands/AddTagCommand.java
- src/main/java/seedu/project/logic/commands/DefineTagCommand.java
- src/main/java/seedu/project/logic/parser/AddTagCommandParser.java
- src/main/java/seedu/project/logic/parser/ProjectParser.java
- src/main/java/seedu/project/model/ProjectList.java
- src/main/java/seedu/project/model/ReadOnlyProjectList.java
> [v1.4] Add group tag to task feature

- docs/DeveloperGuide.adoc
> [v1.3] Update Developer Guide with updated import/export implementation

- docs/UserGuide.adoc
> [v1.3] Update User Guide with import/export and command summary

- src/main/java/seedu/project/logic/commands/ImportCommand.java
- src/main/java/seedu/project/ui/MainWindow.java
> [v1.3] Bug when importing project and panel shading

- docs/DeveloperGuide.adoc
- docs/team/josephinetanadi.adoc
> [v1.4] Update Project Portfolio Page for Mock Submission - josephinetanadi

- docs/team/rachellim10.adoc
- src/main/java/seedu/project/commons/core/Messages.java
- src/main/java/seedu/project/logic/commands/AnalyseCommand.java
- src/main/java/seedu/project/logic/commands/CompletedCommand.java
- src/main/java/seedu/project/logic/parser/ProjectParser.java
> [v1.4] Add AnalyseCommand for statistics

- src/main/java/seedu/project/logic/commands/AnalyseCommand.java
> [v1.4] Update AnalyseCommand to show percentage completed

- src/main/java/seedu/project/logic/commands/AddCommand.java
- src/main/java/seedu/project/model/util/SampleDataUtil.java
- src/test/data/JsonProjectStorageTest/invalidAndValidTask.json
- src/test/data/JsonProjectStorageTest/invalidTask.json
- src/test/data/JsonSerializableProjectListTest/duplicateProject.json
- src/test/data/JsonSerializableProjectListTest/duplicateTask.json
- src/test/data/JsonSerializableProjectListTest/invalidTask.json
- src/test/data/JsonSerializableProjectListTest/typicalProject.json
- src/test/data/JsonSerializableProjectTest/duplicateTask.json
- src/test/data/JsonSerializableProjectTest/typicalTasks.json
- src/test/java/seedu/project/logic/commands/CommandTestUtil.java
- src/test/java/seedu/project/logic/parser/ParserUtilTest.java
- src/test/java/seedu/project/model/task/DeadlineTest.java
- src/test/java/seedu/project/model/task/NameContainsKeywordsPredicateTest.java
- src/test/java/seedu/project/testutil/TaskBuilder.java
- src/test/java/seedu/project/testutil/TypicalTasks.java
- src/test/java/seedu/project/ui/TaskListPanelTest.java
Change date and month format to 01-01-2019
> [v1.4] Update date and month format

- docs/UserGuide.adoc
- src/main/java/seedu/project/logic/commands/AddTagCommand.java
- src/main/java/seedu/project/logic/commands/DefineTagCommand.java
- src/main/java/seedu/project/logic/commands/ListTagCommand.java
- src/main/java/seedu/project/logic/parser/ProjectParser.java
- src/main/java/seedu/project/model/Model.java
- src/main/java/seedu/project/model/ModelManager.java
- src/test/java/seedu/project/logic/commands/AddCommandTest.java
Closes #155 
Closes #152  
Closes #164
> [v1.4] Fix bugs in AddTagCommand and DefineTagCommand

- src/main/java/seedu/project/logic/commands/SelectCommand.java
- src/main/java/seedu/project/model/task/Task.java
- src/main/java/seedu/project/ui/BrowserPanel.java
- src/main/java/seedu/project/ui/MainWindow.java
- src/main/resources/view/BrowserPanel.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/test/java/guitests/guihandles/BrowserPanelHandle.java
- src/test/java/guitests/guihandles/WebViewUtil.java
- src/test/java/seedu/project/ui/BrowserPanelTest.java
- src/test/java/systemtests/HelpCommandSystemTest.java
- src/test/java/systemtests/ProjectSystemTest.java
- src/test/java/systemtests/SelectCommandSystemTest.java
Closes #153 
Closes #162 
Closes #171
> [v1.4] Update Browser Panel to Display task

- src/main/java/seedu/project/logic/commands/SelectCommand.java
- src/main/java/seedu/project/ui/MainWindow.java
> [v1.4] Bug for selecting project and adding task and selecting task

- src/main/java/seedu/project/logic/commands/AnalyseCommand.java
> Fix 'percentage displayed' bug in AnalyseCommand

- src/main/java/seedu/project/logic/commands/UndoCommand.java
- src/main/java/seedu/project/model/Model.java
- src/main/java/seedu/project/model/ModelManager.java
- src/main/java/seedu/project/model/project/UniqueProjectList.java
- src/main/java/seedu/project/model/util/SampleDataUtil.java
- src/main/java/seedu/project/ui/MainWindow.java
- src/main/java/seedu/project/ui/TaskListPanel.java
- src/test/java/seedu/project/TestApp.java
- src/test/java/seedu/project/logic/commands/AddCommandTest.java
- src/test/java/seedu/project/logic/commands/CommandTestUtil.java
- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/ExportCommandSystemTest.java
- src/test/java/systemtests/ImportCommandSystemTest.java
- src/test/java/systemtests/ProjectSystemTest.java
> [v1.4] Update import and export system test

- docs/UserGuide.adoc
- src/main/java/seedu/project/logic/commands/AddTagCommand.java
- src/main/java/seedu/project/logic/commands/DefineTagCommand.java
- src/main/java/seedu/project/logic/commands/ListTagCommand.java
- src/main/java/seedu/project/model/Model.java
- src/main/java/seedu/project/model/ModelManager.java
- src/test/java/seedu/project/logic/commands/AddCommandTest.java
- src/test/java/seedu/project/logic/commands/AddTagCommandTest.java
- src/test/java/seedu/project/logic/commands/CommandTestUtil.java
- src/test/java/seedu/project/logic/commands/DefineTagCommandTest.java
- src/test/java/seedu/project/logic/commands/ListTagCommandTest.java
> [v1.4] Add test codes for DefineTag, AddTag and ListTag

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/josephinetanadi.adoc
> [v1.4] Update Project Portfolio for Final Submission - josephinetanadi

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/rachellim10.adoc
> [v1.4] Update minor changes to UG, DG and PPP

- README.adoc
- docs/ContactUs.adoc
- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/andreathniah.adoc
- docs/templates/_header.html.slim
> [v1.4] Rearrange GitHub pages for submission
